### ISSUE TITLE
Setup simple environment with Docker over openSuSE

### ISSUE THREAD

**Issue by fernandohackbart** [fernandohackbart/bikeride-lagom#133]
* Install openSuSE
`docker: 192.168.1.200`

* Install Docker package
`zypper install -y Docker`
```
S  | Name                            | Summary                                                                     | Type
---+---------------------------------+-----------------------------------------------------------------------------+--------
i+ | docker                          | The Linux container runtime                                                 | package
i  | docker-bash-completion          | Bash Completion for docker                                                  | package
i  | docker-image-migrator           | No-downtime migration tool for Docker v1 image manifests.                   | package
i  | docker-libnetwork               | Docker Networking                                                           | package
i  | docker-runc                     | Tool for spawning and running OCI containers                                | package
i  | docker-zsh-completion           | Zsh Completion for docker                                                   | package
```

**Comment by fernandohackbart** [comment]
* Install Java
`zypper install -y java java-1_8_0-openjdk  java-1_8_0-openjdk-devel `

**Comment by fernandohackbart** [comment]
* Install SBT
```
mkdir /opt/sbt/stage
cd /opt/sbt/stage
wget https://cocl.us/sbt01316tgz
tar xvzf sbt01316tg
mv sbt/* ..
mv /etc/inputrc /etc/inputrc-ignore
```

**Comment by fernandohackbart** [comment]
* Run Jenkins
`docker run --name jenkins -d -p 8080:8080 -p 50000:50000 -v /opt/docker/jenkins/jenkins_home:/var/jenkins_home jenkins/jenkins:lts`

```
docker stop jenkins
docker start jenkins
```

**Comment by fernandohackbart** [comment]
* Run BIND
`docker pull sameersbn/bind`
`docker run --name bind -d --restart=always -p 53:53/tcp -p 53:53/udp -p 10000:10000/tcp --volume /opt/docker/bind:/data sameersbn/bind`

**Comment by fernandohackbart** [comment]
* Configure host to lookup over bind
  * Using yast2

```
cat /etc/resolv.conf
nameserver 172.17.0.2
nameserver 192.168.1.1
```

**Comment by fernandohackbart** [comment]
* Create bikeride.com master DNS zone

http://192.168.1.200:1000

![screenshot-2017-10-7 bind dns server webmin 1 840 on c30b4588dee4 ubuntu linux 14 04 5 1](https://user-images.githubusercontent.com/26771657/31305073-59093868-ab31-11e7-8521-c632983689a7.png)

![screenshot-2017-10-7 bind dns server webmin 1 840 on c30b4588dee4 ubuntu linux 14 04 5](https://user-images.githubusercontent.com/26771657/31305075-5b0e4874-ab31-11e7-888f-08482d37a824.png)

**Comment by fernandohackbart** [comment]
* Create bikeride network

To create
```
docker network ls
docker network create --driver bridge --subnet=172.18.0.0/16 bikeride-network
```

To remove
```
docker network rm bikeride-network
```

**Comment by fernandohackbart** [comment]
* Run Cassandra

```
docker pull cassandra
docker run -d --name cassandra --network bikeride-network --ip 172.18.0.2 -p  9042:9042 -i cassandra
```

```
docker start cassandra
docker attach cassandra
docker stop cassandra
```

**Comment by fernandohackbart** [comment]
* Run Kafka
```
docker pull spotify/kafka
docker run -d --name kafka --network bikeride-network --ip 172.18.0.4 -p  9094:9094 -i spotify/kafka
```
```
docker start kafka
docker attach kafka
docker stop kafka
```

**Comment by fernandohackbart** [comment]
* Run Cassandra CQLSH (when required)

From ouside the host
docker run -it --name cassandra-cqlsh --rm cassandra sh -c 'exec cqlsh "192.168.1.200"'

From inside the host
docker run -it --name cassandra-cqlsh --link cassandra --network bikeride-network --ip 172.18.0.5 --rm cassandra sh -c 'exec cqlsh "172.18.0.3"'

**Comment by fernandohackbart** [comment]
Using the hostname should work

```
docker:/opt/docker/bind/bind # docker run -it --name cassandra-cqlsh --link cassandra --network bikeride-network --ip 172.18.0.5 --rm cassandra sh -c 'exec cqlsh "cassandra.bikeride.com"'
Traceback (most recent call last):
  File "/usr/bin/cqlsh.py", line 2428, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/usr/bin/cqlsh.py", line 2407, in main
    encoding=options.encoding)
  File "/usr/bin/cqlsh.py", line 479, in __init__
    load_balancing_policy=WhiteListRoundRobinPolicy([self.hostname]),
  File "/usr/share/cassandra/lib/cassandra-driver-internal-only-3.10.zip/cassandra-driver-3.10/cassandra/policies.py", line 417, in __init__
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by fernandohackbart** [comment]
If needed to clean some brtfs volumes lost 
`docker:/var/lib/docker # btrfs subvolume delete btrfs/subvolumes/*`

**Comment by fernandohackbart** [comment]
If need to inspect the network

http://jodies.de/ipcalc

```
docker network inspect bridge
docker network inspect bikeride-network
```
