### ISSUE TITLE
ENTRYPOINT should go back to prompt

### ISSUE THREAD

**Issue by fernandohackbart** [fernandohackbart/bikeride-lagom#136]
The docker run command is hanging in the startup of the service

**Comment by fernandohackbart** [comment]
Should nohup to /dev/null the command

**Comment by fernandohackbart** [comment]
Or just adding a -d solve the issue?

**Comment by fernandohackbart** [comment]
```

docker build -f /opt/bikeride/bikeride-lagom/Docker/authentication-lagom-impl/Dockerfile  -t  bikeride/authentication-lagom-impl:0.0.1-SNAPSHOT /opt/bikeride/bikeride-lagom/Docker/authentication-lagom-impl
docker build -f /opt/bikeride/bikeride-lagom/Docker/biker-lagom-impl/Dockerfile  -t  bikeride/biker-lagom-impl:0.0.1-SNAPSHOT /opt/bikeride/bikeride-lagom/Docker/biker-lagom-impl


docker run -d --name authentication1 --network bikeride-network --ip 172.18.0.41 --dns=172.18.0.100 -p 9000:9000 bikeride/authentication-lagom-impl:0.0.1-SNAPSHOT
docker run -d --name biker1 --network bikeride-network --ip 172.18.0.31 --dns=172.18.0.100 -p 9001:9000 bikeride/biker-lagom-impl:0.0.1-SNAPSHOT

docker run -t --name authentication1 --network bikeride-network --ip 172.18.0.41 --dns=172.18.0.100 -p 9000:9000 bikeride/authentication-lagom-impl:0.0.1-SNAPSHOT
docker run -t --name biker1 --network bikeride-network --ip 172.18.0.31 --dns=172.18.0.100 -p 9001:9000 bikeride/biker-lagom-impl:0.0.1-SNAPSHOT



curl -d {"client":{"clientID":"f0891f51-4fb5-4881-9605-f00e481241d2"},"email":"biker2@bikers.com"} -H "Content-Type: application/json" -X POST http://authentication.api.bikeride.com:8000/api/authn/generatepin
curl -d {"client":{"clientID":"f0891f51-4fb5-4881-9605-f00e481241d2"},"email":"biker2@bikers.com"} -H "Content-Type: application/json" -X POST http://authentication1.container.bikeride.com:9000/api/authn/generatepin


curl http://biker.api.bikeride.com:8000/api/bikers
curl http://biker1.container.bikeride.com:9001/api/bikers



curl -d {"client":{"clientID":"f0891f51-4fb5-4881-9605-f00e481241d2"},"email":"biker2@bikers.com"} -H "Content-Type: application/json" -X POST http://authentication1.container.bikeride.com:9000/api/authn/biker



curl -d '{"client":{"clientID":"3fa69cf5-0783-494c-a929-e1aac72541d9"},"bikerFields":{"name":"Biker1","avatarb64":"picturebiker1","bloodType":"O-","mobile":"+555135900001","email":"biker1@bikers.com","active":true}}'  -H "Content-Type: application/json" -X POST http://authentication.api.bikeride.com:8000/api/authn/biker

curl -d '{"client":{"clientID":"3fa69cf5-0783-494c-a929-e1aac72541d9"},"bikerFields":{"name":"Biker1","avatarb64":"picturebiker1","bloodType":"O-","mobile":"+555135900001","email":"biker1@bikers.com","active":true}}'  -H "Content-Type: application/json" -X POST http://localhost:9000/api/authn/biker





docker run -t --name biker1 --network bikeride-network --ip 172.18.0.31 -p 9001:9000 bikeride/biker-lagom-impl:0.0.1-SNAPSHOT
```

**Comment by fernandohackbart** [comment]
```
21:20:06.677 [debug] com.bikeride.utils.servicelocator.dns.ServiceLocator [sourceThread=application-akka.actor.default-dispatcher-2, akkaTimestamp=21:20:06.677UTC, akkaSource=akka.tcp://application@172.18.0.41:2552/user/DNSServiceLocatorSimple, sourceActorSystem=application] - ###################### resolveSrv - Translated biker to _biker._tcp.biker.api.bikeride.com
21:20:06.680 [debug] com.bikeride.utils.servicelocator.dns.ServiceLocator [sourceThread=application-akka.actor.default-dispatcher-19, akkaTimestamp=21:20:06.680UTC, akkaSource=akka.tcp://application@172.18.0.41:2552/user/DNSServiceLocatorSimple, sourceActorSystem=application] - ###################### resolveSrv - Serrvice translated from _biker._tcp.biker.api.bikeride.com to _biker._http.biker.api.bikeride.com
21:20:06.680 [debug] com.bikeride.utils.servicelocator.dns.ServiceLocator [sourceThread=application-akka.actor.default-dispatcher-3, akkaTimestamp=21:20:06.680UTC, akkaSource=akka.tcp://application@172.18.0.41:2552/user/DNSServiceLocatorSimple, sourceActorSystem=application] - ###################### resolved: Vector(ServiceAddress(http,biker.api.bikeride.com,172.18.0.20,8000))
21:20:06.691 [error] authn [] - Exception in RestCallIdImpl(POST,/api/authn/biker)
com.lightbend.lagom.scaladsl.api.transport.PolicyViolation: {"message":"no API found with those values"}

        at com.lightbend.lagom.scaladsl.api.transport.TransportException$$anonfun$14.apply(Exceptions.scala:241)
        at com.lightbend.lagom.scaladsl.api.transport.TransportException$$anonfun$14.apply(Exceptions.scala:241)
        at com.lightbend.lagom.scaladsl.api.transport.TransportException$$anonfun$fromCodeAndMessage$3.apply(Exceptions.scala:223)
        at com.lightbend.lagom.scaladsl.api.transport.TransportException$$anonfun$fromCodeAndMessage$3.apply(Exceptions.scala:223)
        at scala.Option.fold(Option.scala:158)
        at com.lightbend.lagom.scaladsl.api.transport.TransportException$.fromCodeAndMessage(Exceptions.scala:223)
        at com.lightbend.lagom.scaladsl.api.deser.DefaultExceptionSerializer.fromCodeAndMessage(ExceptionSerializer.scala:114)
        at com.lightbend.lagom.scaladsl.api.deser.DefaultExceptionSerializer.deserialize(ExceptionSerializer.scala:100)
        at com.lightbend.lagom.internal.scaladsl.client.ScaladslServiceApiBridge$class.exceptionSerializerDeserializeHttpException(ScaladslServiceApiBridge.scala:82)
        at com.lightbend.lagom.internal.scaladsl.client.ScaladslClientServiceCallInvoker.exceptionSerializerDeserializeHttpException(ScaladslServiceClientInvoker.scala:110)
        at com.lightbend.lagom.internal.scaladsl.client.ScaladslClientServiceCallInvoker.exceptionSerializerDeserializeHttpException(ScaladslServiceClientInvoker.scala:110)
        at com.lightbend.lagom.internal.client.ClientServiceCallInvoker$$anonfun$com$lightbend$lagom$internal$client$ClientServiceCallInvoker$$makeStrictCall$1.apply(ClientServiceCallInvoker.scala:219)
        at com.lightbend.lagom.internal.client.ClientServiceCallInvoker$$anonfun$com$lightbend$lagom$internal$client$ClientServiceCallInvoker$$makeStrictCall$1.apply(ClientServiceCallInvoker.scala:208)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by fernandohackbart** [comment]
Solved with -d
