### ISSUE TITLE
None.get after creating biker with empty fields

### ISSUE THREAD

**Issue by fernandohackbart** [fernandohackbart/bikeride-lagom#152]
```
04:28:52.065 [error] akka.actor.OneForOneStrategy [sourceThread=application-akka.actor.default-dispatcher-18, akkaTimestamp=04:28:52.064UTC, akkaSource=akka://application/system/sharding/BikerEventProcessor/com.bikeride.biker.impl.BikerEvent1/com.bikeride.biker.impl.BikerEvent1/processor, sourceActorSystem=application] - None.get
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at com.bikeride.biker.impl.BikerEventProcessor$$anonfun$com$bikeride$biker$impl$BikerEventProcessor$$processBikerCreated$1.apply(BikerEventProcessor.scala:102)
        at com.bikeride.biker.impl.BikerEventProcessor$$anonfun$com$bikeride$biker$impl$BikerEventProcessor$$processBikerCreated$1.apply(BikerEventProcessor.scala:96)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by fernandohackbart** [comment]
```
      if (!eventElement.event.biker.avatarb64.isEmpty) bindInsertBiker.setString("avatarb64", eventElement.event.biker.avatarb64.get)
      if (!eventElement.event.biker.bloodType.isEmpty) bindInsertBiker.setString("bloodtype", eventElement.event.biker.bloodType.get)
      if (!eventElement.event.biker.mobile.isEmpty) bindInsertBiker.setString("mobile", eventElement.event.biker.mobile.get)
      if (!eventElement.event.biker.email.isEmpty) bindInsertBiker.setString("email", eventElement.event.biker.email.get)

```

**Comment by fernandohackbart** [comment]
Done
